<a href="https://colab.research.google.com/github/project20190103/1224/blob/master/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd
import scipy.signal as sg
import random
import math

In [ ]:
pi = np.pi
exp = np.exp
def dft(x):
    N = len(x)
    ks = range(N)
    args = -2j * pi * np.outer(ks, ks) / N
    W = exp(args)
    X = W.dot(x)
    return X

In [ ]:
x3 = [1,-1,1,-1,1,-1,1,-1]
dft(x3)

array([ 0.00000000e+00+0.00000000e+00j,  3.83475851e-17-4.44089210e-16j,
        2.44929360e-16-2.44929360e-16j,  8.84157967e-16-1.55431223e-15j,
        8.00000000e+00+3.42901104e-15j, -2.69484194e-15+0.00000000e+00j,
        2.81792560e-15-7.34788079e-16j, -5.26443671e-15-2.77555756e-15j])

##1


In [ ]:
def iexp(n):
    return complex(math.cos(n), math.sin(n))
    
def dft(xs):
    "naive dft"
    n = len(xs)
    return [sum((xs[k] * iexp(-2 * math.pi * i * k / n) for k in range(n)))
            for i in range(n)]

def dftinv(xs):
    "naive dft"
    n = len(xs)
    return [sum((xs[k] * iexp(2 * math.pi * i * k / n) for k in range(n))) / n
            for i in range(n)]

In [ ]:
x1 = [1,0,0,0,0,0,0,0]
dft(x1)


array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

(b)

In [ ]:
x2 = [1,1,1,1,1,1,1,1]
dft(x2)

array([ 8.00000000e+00+0.00000000e+00j, -4.05741625e-16+0.00000000e+00j,
       -2.44929360e-16-2.44929360e-16j, -2.26065058e-16+8.88178420e-16j,
        0.00000000e+00-4.89858720e-16j, -2.25075273e-15-1.33226763e-15j,
       -2.81792560e-15-7.34788079e-16j,  3.39530289e-15+9.99200722e-16j])

(c)

In [ ]:
x3 = [1,-1,1,-1,1,-1,1,-1]
dft(x3)

array([ 0.00000000e+00+0.00000000e+00j,  3.83475851e-17-4.44089210e-16j,
        2.44929360e-16-2.44929360e-16j,  8.84157967e-16-1.55431223e-15j,
        8.00000000e+00+3.42901104e-15j, -2.69484194e-15+0.00000000e+00j,
        2.81792560e-15-7.34788079e-16j, -5.26443671e-15-2.77555756e-15j])

(d)

In [ ]:
a = np.array(x1)
b = np.array(x2)
c = np.array(x3)
x4 = a+b+c
dft(x4)

array([9.+0.00000000e+00j, 1.-4.44089210e-16j, 1.-4.89858720e-16j,
       1.-6.66133815e-16j, 9.+2.93915232e-15j, 1.-1.33226763e-15j,
       1.-1.46957616e-15j, 1.-1.77635684e-15j])

(f)

In [ ]:
X5 = [1,1,0,0,0,0,1,1]
X6 = [1,1,0,0,0,0,0,1]
dftinv(X5)

[(0.5+0j),
 (0.3017766952966368-0.12500000000000003j),
 (-5.35782974626967e-17+5.551115123125783e-17j),
 (-0.05177669529663678+0.12499999999999997j),
 3.0616169978683836e-17j,
 (-0.05177669529663707-0.12499999999999982j),
 (-8.906528815257012e-17+1.3877787807814457e-16j),
 (0.3017766952966372+0.12499999999999961j)]

In [ ]:
dftinv(X6)

[(0.375+0j),
 (0.30177669529663687-2.7755575615628914e-17j),
 (0.12499999999999994+0j),
 (-0.05177669529663685-1.3877787807814457e-17j),
 (-0.125+1.2246467991473532e-16j),
 (-0.05177669529663673+1.8041124150158794e-16j),
 (0.12499999999999992+0j),
 (0.30177669529663725-3.885780586188048e-16j)]

In [ ]:
(g)

In [ ]:
x7 = [1,1,0,0]
dft(x7)



array([2.+0.0000000e+00j, 1.-1.0000000e+00j, 0.-1.2246468e-16j,
       1.+1.0000000e+00j])

In [ ]:
x8 = [1,1,0,0,0,0,0,0]
dft(x8)

array([2.        +0.00000000e+00j, 1.70710678-7.07106781e-01j,
       1.        -1.00000000e+00j, 0.29289322-7.07106781e-01j,
       0.        -1.22464680e-16j, 0.29289322+7.07106781e-01j,
       1.        +1.00000000e+00j, 1.70710678+7.07106781e-01j])

##2


(a)

In [ ]:
f = np.random.randint(1,100,3)
g = np.random.randint(1,100,3)
print(f)
print(g)

[44 22 63]
[91 74 60]


In [ ]:
np.convolve(f,g,mode='valid'),\
np.convolve(f,g,mode='same'),\
np.convolve(f,g,mode='full')

(array([10001]),
 array([ 5258, 10001,  5982]),
 array([ 4004,  5258, 10001,  5982,  3780]))

(b)

In [ ]:
x= np.array([1,1,1,1])

w= np.array([1,1])

np.convolve(x,w,mode='valid'),\
np.convolve(x,w,mode='same'),\
np.convolve(x,w,mode='full')

(array([2, 2, 2]), array([1, 2, 2, 2]), array([1, 2, 2, 2, 1]))

##3


(a)

摺積定理指出，函數摺積的傅立葉轉換是函數傅立葉轉換的乘積。即一個域中的摺積對應於另一個域中的乘積，例如時域中的摺積對應於頻域中的乘積。

